plugins {
	id 'dev.architectury.loom'
}

repositories {
	maven {
		name = 'Terraformers'
		url = 'https://maven.terraformersmc.com/'
	}
}

dependencies {
	implementation project(':base')
	minecraft "net.minecraft:minecraft:${project.minecraft_version}"
	mappings loom.officialMojangMappings()
	modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"

	modImplementation "com.terraformersmc:modmenu:${project.modmenu_version}"
}

loom {
	mixin {
		defaultRefmapName = "${project.archives_base_name}-fabric-refmap.json"
	}

	runs {
		remove server
	}
}

processResources {
	filesMatching('fabric.mod.json') {
		expand inputs.properties
	}
}

processTestResources {
	filesMatching('fabric.mod.json') {
		expand inputs.properties
	}
}

java.withSourcesJar()
