plugins {
	id 'dev.architectury.loom'
}

repositories {
	maven {
		name = 'Terraformers'
		url = 'https://maven.terraformersmc.com/'
	}
}

dependencies {
	implementation project(':base')
	minecraft group: 'net.minecraft', name: 'minecraft', version: project.minecraft_version
	mappings loom.officialMojangMappings()
	modImplementation group: 'net.fabricmc', name: 'fabric-loader', version: project.loader_version

	modImplementation group: 'com.terraformersmc', name: 'modmenu', version: project.modmenu_version
}

loom {
	mixin {
		defaultRefmapName = "${project.archives_base_name}-fabric-refmap.json"
	}
}

processResources {
	filesMatching('fabric.mod.json') {
		expand inputs.properties
	}
}

processTestResources {
	filesMatching('fabric.mod.json') {
		expand inputs.properties
	}
}
