plugins {
	id 'dev.architectury.loom' version "${loom_version}" apply false
}

var base = findProject(':base')
var fabric = findProject(':fabric')
var forge = findProject(':forge')

allprojects {
	apply plugin: 'java'

	java.toolchain.languageVersion = JavaLanguageVersion.of(8)

	var replaceProperties = [
		version: project.version,
		license: project.license,
	]

	processResources {
		inputs.properties replaceProperties
	}

	processTestResources {
		inputs.properties replaceProperties
	}

	tasks.withType(JavaCompile).configureEach {
		options.encoding = 'UTF-8'
	}
}

subprojects {
	apply plugin: 'java'

	it.base {
		archivesName = "${project.archives_base_name}-${project.display_name}"
	}

	jar {
		from '../LICENSE'
	}
}

def generateManifestAttributes() {
	var attributes = [
		'Built-Timestamp': new Date(),
		'Built-OS': System.getProperty('os.name'),
	]
	var githubActions = System.getenv('GITHUB_ACTIONS')
	var githubSha = System.getenv('GITHUB_SHA')
	var termProgram = System.getenv('TERM_PROGRAM')
	if (githubActions != null) attributes['Built-GitHub-Actions'] = githubActions
	if (githubSha != null) attributes['Built-GitHub-Sha'] = githubSha
	if (termProgram != null) attributes['Built-Term-Program'] = termProgram
	return attributes
}

jar {
	if (base != null) evaluationDependsOn(base.getName())
	if (fabric != null) evaluationDependsOn(fabric.getName())
	if (forge != null) evaluationDependsOn(forge.getName())

	var baseJar = base != null ? base.tasks.getByName('jar') : null
	var fabricJar = fabric != null ? fabric.tasks.getByName('jar') : null
	var fabricRemapJar = fabric != null ? fabric.tasks.getByName('remapJar') : null
	var forgeJar = forge != null ? forge.tasks.getByName('jar') : null
	var forgeRemapJar = forge != null ? forge.tasks.getByName('remapJar') : null

	from 'LICENSE'
	if (baseJar != null) from(zipTree(baseJar.archiveFile)) {
		exclude 'LICENSE'
	}
	if (fabricRemapJar != null) from(zipTree(fabricRemapJar.archiveFile)) {
		exclude 'LICENSE'
	}
	if (forgeRemapJar != null) from(zipTree(forgeRemapJar.archiveFile)) {
		exclude 'LICENSE'
	}

	manifest {
		if (baseJar != null) from baseJar.manifest
		if (fabricJar != null) from fabricJar.manifest
		if (forgeJar != null) from forgeJar.manifest
		attributes(generateManifestAttributes())
	}
}
