plugins {
	id 'dev.architectury.loom'
}

dependencies {
	implementation project(':base')
	minecraft group: 'net.minecraft', name: 'minecraft', version: project.minecraft_version
	mappings loom.officialMojangMappings()
	forge group: 'net.minecraftforge', name: 'forge', version: "${project.minecraft_version}-${project.forge_version}"
}

loom {
	mixin {
		defaultRefmapName = "${project.archives_base_name}-forge-refmap.json"
	}

	forge {
		mixinConfigs = ['mixins.musicpack.forge.json']
	}
}

processResources {
	filesMatching('META-INF/mods.toml') {
		expand inputs.properties
	}
}

processTestResources {
	filesMatching('META-INF/mods.toml') {
		expand inputs.properties
	}
}
