plugins {
	id 'dev.architectury.loom'
}

dependencies {
	implementation project(':core')
	minecraft "net.minecraft:minecraft:${project.minecraft_version}"
	mappings loom.officialMojangMappings()
	forge "net.minecraftforge:forge:${project.minecraft_version}-${project.forge_version}"
}

loom {
	mixin {
		defaultRefmapName = "${project.archives_base_name}-forge-refmap.json"
	}

	forge {
		mixinConfigs = ['mixins.musicpack.forge.json']
	}

	runs {
		remove server
	}
}

processResources {
	filesMatching('META-INF/mods.toml') {
		expand inputs.properties
	}
}

processTestResources {
	filesMatching('META-INF/mods.toml') {
		expand inputs.properties
	}
}

java.withSourcesJar()
