plugins {
	id 'java'
}

repositories {
	maven {
		name = 'MinecraftLibs'
		url = 'https://libraries.minecraft.net'
	}

	mavenCentral()
}

dependencies {
	compileOnly "com.google.code.gson:gson:${project.gson_version}"
	compileOnly "com.google.guava:guava:${project.google_guava_version}"
	compileOnly "org.apache.logging.log4j:log4j-api:${project.log4j_version}"
}
