name: Release
on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
        description: Версия
      tag_suffix:
        type: string
        required: false
        description: Суфикс тэга
      recommended:
        type: boolean
        required: true
        default: false
        description: Рекомендуемый
jobs:
  draft_release:
    name: Draft a new release
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
      - name: Configure Git Actions Bot
        uses: drengskapur/gitbot-config@00aecab0a790b146951f9e0c48f564eaf26a9df6
      - name: Run script
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { version, tag_suffix: suffix, recommended } = context.payload.inputs
            const versionMatch = version.match(/^(?<num>\d+\.\d+\.\d+)(-(?<pre>[a-z]+\d+))?$/)
            if (!versionMatch) throw new TypeError(`Invalid version ${version}`)
            const { num, pre } = versionMatch.groups
            const head = `chore/release-${version}`, title = `chore: Релиз обновления ${version}`

            const { execSync } = require('node:child_process')
            const fs = require('node:fs')
            const path = require('node:path')

            execSync(`sed -i "s/^version\s*=\s*.\\+$/version=${version}/g" gradle.properties`)
            const updatePath = path.resolve('update.json')
            const update = JSON.parse(fs.readFileSync(updatePath, 'utf8'))
            for (const minecraftVersion in update.promos) {
              const { type } = minecraftVersion.match(/^(?<num>\d+\.\d+(\.\d+)?)-(?<type>latest|recommended)$/).groups
              if (type === 'recommended' && recommended !== 'true') continue
              update.promos[minecraftVersion] = version
            }
            fs.writeFileSync(updatePath, `${JSON.stringify(update, null, '\t')}\n`, 'utf8')

            execSync('git diff gradle.properties update.json')
            execSync(`git checkout -b ${head}`)
            execSync('git add gradle.properties update.json')
            execSync(`git commit -m "${title}"`)
            execSync(`git push origin ${head}`)

            const data = {
              owner: context.repo.owner,
              repo: context.repo.repo
            }

            const pr = await github.rest.pulls.create({ ...data, title, head, base: 'main' })
            await github.rest.issues.addLabels({ ...data, issue_number: pr.data.number, labels: ['release'] })
            await github.rest.repos.createRelease({ ...data, tag_name: `${version}${suffix ? `-${suffix}` : ''}`, name: `v${version}`, draft: true, prerelease: pre !== undefined })
